### ISSUE TITLE
Can't add runes above the automatic ones

### ISSUE THREAD

**Issue by MrChessur** [reonZ/pf2e-arp#3]
Not sure if this is intended, but some items just have runes higher than the Automatic Progression. When you put them on a character sheet they automatically assign to the progression level. Since adventures sometimes give gear a little earlier, it just makes some of the gear a little worse.

It's not a huge deal since I know it is happening, but if possible it would be nice if magic items that are slightly better than the progression would stay a little better. Or if you could increase them still to be better.

Obviously I may be a minority in this thinking, but I thought I'd bring it up in case it was unintentional as I think early versions used to work fine for this.

**Comment by reonZ** [comment]
That is how it is supposed to work, just like ABP would.

Using such variant rule forces the progression to a level standard and supersedes any manual setup.
