### ISSUE TITLE
Applies runes to companions

### ISSUE THREAD

**Issue by JTorKag** [reonZ/pf2e-arp#4]
When using this module along side companion compendia it applies the scaling to the attacks and weapons of an animal companion. This causes issues as they're scaling higher than they're supposed to. 

I spoke to tikael to creator of companion compendia and he informed me that it would be resolved if your ARP module was configured to "honor the disableABP flag." 

Hopefully that's an easy fix to push out quickly. 

Anyways cheers thanks for the mod.

**Comment by reonZ** [comment]
I pretty much know what i need to do but could you give me a way to reproduce the issue you encounter ?

I tried creating an edolon (because they have weapons) and didn't see any difference between with or without the module enabled

**Comment by JTorKag** [comment]
Hey sorry I didn't get a chance to respond to your request on how to reproduce before you fixed it. I just updated and it's working correctly now! 

Much appreciated.

**Comment by reonZ** [comment]
it's fine, it was my mistake actually.
